config/routes.rb
Rails.application.routes.draw do

  root 'teams#index'
  resources :teams

end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  has_and_belongs_to_many :teams
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players
  has_and_belongs_to_many :sponsors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
    @players = Player.all
  end

  def new
    @team = Team.new
  end

  def create
    Team.create(team_params)
    # If you wanted to avoid calling a separate variable (team params), you'd need to pass the entire whitelist below as an argument into Team.create. This is much cleaner and readable.
    redirect_to(teams_path)
  end

  def show
    @team = Team.find(params[:id])
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    team = Team.find(params[:id])
    team.update(team_params)
    redirect_to(teams_path)
  end

  def destroy
    team = Team.find(params[:id])
    team.destroy
    redirect_to(teams_path)
  end

  private
  def team_params
    params.require(:team).permit(:name, :image, :founded, :mascot, :ground, :league, :last_position)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FantasyLeague</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <ul>
    <li>
      <%= link_to('List Teams', teams_path) %>
    </li>
    <li>
      <%= link_to('New Team', new_team_path) %>
    </li>
  </ul>
</nav>

<%= yield %>

</body>
</html>